//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhiDoan
    {
        public int ID { get; set; }
        public string TenChiPhi { get; set; }
        public int ChiPhiThucTe { get; set; }
        public int SoLuong { get; set; }
        public int Tong { get; set; }
        public string GhiChu { get; set; }
        public int DoanID { get; set; }
        public int LoaiCP { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual LoaiChiPhi LoaiChiPhi { get; set; }
    }
}
