//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVienDoan
    {
        public int ID { get; set; }
        public int DoanID { get; set; }
        public int NhanVienID { get; set; }
        public int NhiemVuID { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhiemVu NhiemVu { get; set; }
    }
}
