//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiChiPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiChiPhi()
        {
            this.ChiPhiDoans = new HashSet<ChiPhiDoan>();
            this.ChiPhiTours = new HashSet<ChiPhiTour>();
        }
    
        public int ID { get; set; }
        public string TenLoaiCP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiDoan> ChiPhiDoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiTour> ChiPhiTours { get; set; }
    }
}
