//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourCommon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourDBEntities : DbContext
    {
        public TourDBEntities()
            : base("name=TourDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiPhiDoan> ChiPhiDoans { get; set; }
        public virtual DbSet<ChiPhiTour> ChiPhiTours { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<DoanDuLich> DoanDuLiches { get; set; }
        public virtual DbSet<KhachDuLich> KhachDuLiches { get; set; }
        public virtual DbSet<LoaiChiPhi> LoaiChiPhis { get; set; }
        public virtual DbSet<LoaiHinh> LoaiHinhs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanVienDoan> NhanVienDoans { get; set; }
        public virtual DbSet<NhiemVu> NhiemVus { get; set; }
        public virtual DbSet<Tinh> Tinhs { get; set; }
        public virtual DbSet<TinhTrangDoan> TinhTrangDoans { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<ThanhVienDoan> ThanhVienDoans { get; set; }
        public virtual DbSet<DiaDiemTour> DiaDiemTours { get; set; }
    }
}
