//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiem
    {
        public DiaDiem()
        {
            this.DiaDiemTours = new HashSet<DiaDiemTour>();
        }
    
        public int ID { get; set; }
        public string TenDiaDiem { get; set; }
        public int TinhID { get; set; }
    
        public virtual Tinh Tinh { get; set; }
        public virtual ICollection<DiaDiemTour> DiaDiemTours { get; set; }
    }
}
