//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiemTour
    {
        public System.DateTime Ngay { get; set; }
        public int TourID { get; set; }
        public int DiaDiemID { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
