//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiChiPhi
    {
        public LoaiChiPhi()
        {
            this.ChiPhiDoans = new HashSet<ChiPhiDoan>();
            this.ChiPhiTours = new HashSet<ChiPhiTour>();
        }
    
        public int ID { get; set; }
        public string TenLoaiCP { get; set; }
    
        public virtual ICollection<ChiPhiDoan> ChiPhiDoans { get; set; }
        public virtual ICollection<ChiPhiTour> ChiPhiTours { get; set; }
    }
}
