//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVienDoan
    {
        public int ID { get; set; }
        public int TyLeTraLai { get; set; }
        public int DoanID { get; set; }
        public int KhachID { get; set; }
    
        public virtual DoanDuLich DoanDuLich { get; set; }
        public virtual KhachDuLich KhachDuLich { get; set; }
    }
}
