//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangDoan
    {
        public TinhTrangDoan()
        {
            this.DoanDuLiches = new HashSet<DoanDuLich>();
        }
    
        public int ID { get; set; }
        public string TenTinhTrang { get; set; }
    
        public virtual ICollection<DoanDuLich> DoanDuLiches { get; set; }
    }
}
