//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourDBEntities : DbContext
    {
        public TourDBEntities()
            : base("name=TourDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiPhiDoan> ChiPhiDoans { get; set; }
        public DbSet<ChiPhiTour> ChiPhiTours { get; set; }
        public DbSet<DiaDiem> DiaDiems { get; set; }
        public DbSet<DoanDuLich> DoanDuLiches { get; set; }
        public DbSet<KhachDuLich> KhachDuLiches { get; set; }
        public DbSet<LoaiChiPhi> LoaiChiPhis { get; set; }
        public DbSet<LoaiHinh> LoaiHinhs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhanVienDoan> NhanVienDoans { get; set; }
        public DbSet<NhiemVu> NhiemVus { get; set; }
        public DbSet<Tinh> Tinhs { get; set; }
        public DbSet<TinhTrangDoan> TinhTrangDoans { get; set; }
        public DbSet<Tour> Tours { get; set; }
        public DbSet<ThanhVienDoan> ThanhVienDoans { get; set; }
        public DbSet<DiaDiemTour> DiaDiemTours { get; set; }
    }
}
